# ZUBIN JAMES PALIT
# 20BEC0088

**ASSIGNMENT - 1**

In [2]:
import numpy as np
import pandas as pd

In [3]:
s1=pd.Series(np.random.rand(4))
s2=pd.Series(np.random.rand(4))
s3=pd.Series(np.random.rand(4))
s4=pd.Series(np.random.rand(4))

print(s1)
print(s2)
print(s3)
print(s4)

0    0.360394
1    0.562679
2    0.455271
3    0.954886
dtype: float64
0    0.327060
1    0.668666
2    0.951681
3    0.767409
dtype: float64
0    0.205808
1    0.192458
2    0.143765
3    0.039269
dtype: float64
0    0.831518
1    0.603273
2    0.935992
3    0.399160
dtype: float64

In [13]:
df=pd.DataFrame([s1,s2,s3,s4])
df=df.T

In [14]:
df.columns=['Random Value 1','Random Value 2','Random Value 3','Random Value 4']
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0        0.360394        0.327060        0.205808        0.831518
1        0.562679        0.668666        0.192458        0.603273
2        0.455271        0.951681        0.143765        0.935992
3        0.954886        0.767409        0.039269        0.399160

In [15]:
df.describe()

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.583307        0.678704        0.145325        0.692486
std          0.261139        0.262132        0.075565        0.239878
min          0.360394        0.327060        0.039269        0.399160
25%          0.431552        0.583264        0.117641        0.552245
50%          0.508975        0.718037        0.168112        0.717396
75%          0.660731        0.813477        0.195796        0.857637
max          0.954886        0.951681        0.205808        0.935992

In [16]:
df.isnull().sum()

Random Value 1    0
Random Value 2    0
Random Value 3    0
Random Value 4    0
dtype: int64

In [17]:
df.dtypes

Random Value 1    float64
Random Value 2    float64
Random Value 3    float64
Random Value 4    float64
dtype: object

In [18]:
df.loc[:,['Random Value 2','Random Value 3']]

   Random Value 2  Random Value 3
0        0.327060        0.205808
1        0.668666        0.192458
2        0.951681        0.143765
3        0.767409        0.039269

In [19]:
df.iloc[:,[1,2]]

   Random Value 2  Random Value 3
0        0.327060        0.205808
1        0.668666        0.192458
2        0.951681        0.143765
3        0.767409        0.039269